Input parsing
gmm97/DD2480 pull request #15
Opened 2022-01-28 11:56 UTC by Dajamante

Parser for standard-formated input files:

# int numpoints
# list points
# double length1
# double radius1
# double epsilon
# double area1
# int Q_PTS
# int quads
# double dist
# int N_PTS
# int K_PTS
# int A_PTS
# int B_PTS
# int C_PTS
# int D_PTS
# int E_PTS
# int F_PTS
# int G_PTS
# double length2
# double radius2
# double area2
# list LCM
# list PUV

2022-01-28 12:14 UTC, ztick requested changes
Very nice work guys, well done!
We just need some documentation and it's ready to merge imo :)

2022-01-28 12:14 UTC, ztick commented on Assignment1/generate_datapoints.py
> +def generate_datatpoints(x):
Please include documentation for each function (short comment explaining what it does, if you're using VScode I recommend the extension "Python Docstring Generator", I just downloaded it and it's really really easy)

2022-01-28 12:14 UTC, ztick commented on Assignment1/generate_datapoints.py
> +    # x = number of points
should these comments be here?

2022-01-28 18:00 UTC, ztick approved these changes
LGTM

2022-01-30 12:47 UTC, gmm97 approved these changes
1) Added assertions for each input in line with conditions given in the problem statement
2) Modified input txt file to format param as NAME=VALUE for better readability
3) Changed output write format to .txt so the formats are consistent for both reading and writing params to file

2022-01-30 14:10 UTC, ztick approved these changes
Nice! You're right about the readability, and the asserts are great functionality.

2022-01-31 11:02 UTC, merged